import type { Task, Timer, Recipe } from './types'

export const INITIAL_TASKS: Task[] = [
  // ── MONDAY JUNE 15 ──────────────────────────────────────────────────────
  { id: 'mon-001', title: 'Reserve two bone-in pork shoulders (6–7 lb each)', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Butcher', priority: 'high', quantity: '2 × 6–7 lb' },
  { id: 'mon-002', title: 'Reserve tri-tip (5.5–6 lb total)', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Butcher', priority: 'high', quantity: '5.5–6 lb total' },
  { id: 'mon-003', title: 'Order or reserve graduation cake', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Bakery', priority: 'high' },
  { id: 'mon-004', title: 'Order two rectangular poly-rattan bread baskets (12–15 in)', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'medium', quantity: '2' },
  { id: 'mon-005', title: 'Order 8–10 white 8 oz ramekins', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'medium', quantity: '8–10' },
  { id: 'mon-006', title: 'Order 4–6 small serving tongs', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'medium', quantity: '4–6' },
  { id: 'mon-007', title: 'Order 4–6 small serving spoons or cocktail forks', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'medium', quantity: '4–6' },
  { id: 'mon-008', title: 'Order two BBQ sauce squeeze bottles or small pitchers', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'medium', quantity: '2' },
  { id: 'mon-009', title: 'Order small wide-mouth bowl/pitcher for chimichurri', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'medium', quantity: '1' },
  { id: 'mon-010', title: 'Order reusable buffet labels or mini chalkboard signs', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'medium' },
  { id: 'mon-011', title: 'Order chalk marker', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'low' },
  { id: 'mon-012', title: 'Order vacuum-sealer bags', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'high' },
  { id: 'mon-013', title: 'Order large disposable foil pans', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'high' },
  { id: 'mon-014', title: 'Order foil-pan lids', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'high' },
  { id: 'mon-015', title: 'Order heavy-duty aluminum foil', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'high' },
  { id: 'mon-016', title: 'Order disposable food-prep gloves', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'medium' },
  { id: 'mon-017', title: 'Order heat-resistant BBQ gloves', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'medium' },
  { id: 'mon-018', title: 'Order thermometer batteries', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'high' },
  { id: 'mon-019', title: 'Order gallon freezer bags', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'medium' },
  { id: 'mon-020', title: 'Order leftover containers', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'medium' },
  { id: 'mon-021', title: 'Order large beverage tub', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'medium' },
  { id: 'mon-022', title: 'Order clean drink-ice bucket', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'medium' },
  { id: 'mon-023', title: 'Order ice scoop', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'low' },
  { id: 'mon-024', title: 'Order small garnish bowls', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'low' },
  { id: 'mon-025', title: 'Order acrylic recipe-card holder', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'low' },
  { id: 'mon-026', title: 'Order wine key', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Amazon', priority: 'low' },
  { id: 'mon-027', title: 'Buy dried pinquito beans', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '2 lb' },
  { id: 'mon-028', title: 'Buy dill pickle chips', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '32–46 oz jar' },
  { id: 'mon-029', title: 'Buy sliced pickled jalapeños', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '12–16 oz jar' },
  { id: 'mon-030', title: 'Buy sliced hot cherry peppers', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'high' },
  { id: 'mon-031', title: 'Buy sweet or smoky BBQ sauce', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '1 bottle' },
  { id: 'mon-032', title: 'Buy tangy vinegar BBQ sauce', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '1 bottle' },
  { id: 'mon-033', title: 'Buy crushed tomatoes', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '28 oz' },
  { id: 'mon-034', title: 'Buy tomato sauce', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '15 oz' },
  { id: 'mon-035', title: 'Buy tomato paste', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'high' },
  { id: 'mon-036', title: 'Buy Worcestershire sauce', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-037', title: 'Buy red wine vinegar', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-038', title: 'Buy cider vinegar', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-039', title: 'Buy white wine vinegar', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-040', title: 'Buy extra-virgin olive oil', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-041', title: 'Buy neutral oil', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-042', title: 'Buy Dijon mustard', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-043', title: 'Buy whole-grain mustard', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-044', title: 'Buy brown sugar', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-045', title: 'Buy white sugar', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-046', title: 'Buy kosher salt', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'high' },
  { id: 'mon-047', title: 'Buy coarse black pepper', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'high' },
  { id: 'mon-048', title: 'Buy paprika', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-049', title: 'Buy granulated garlic', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-050', title: 'Buy onion powder', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-051', title: 'Buy ground cumin', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-052', title: 'Buy chili powder', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-053', title: 'Buy red pepper flakes', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-054', title: 'Buy celery seed', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-055', title: 'Buy dried oregano', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-056', title: 'Buy low-sodium broth or apple juice', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'high' },
  { id: 'mon-057', title: 'Buy two large bags of charcoal', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '2 large bags' },
  { id: 'mon-058', title: 'Buy oak wood chunks', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '4–5 fist-sized chunks needed' },
  { id: 'mon-059', title: 'Buy fire starters', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-060', title: 'Buy long lighter', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-061', title: 'Buy drip pans', category: 'shopping', dueDate: '2026-06-15', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'mon-062', title: 'Confirm both pork shoulders fit on indirect side of Weber', category: 'equipment', dueDate: '2026-06-15', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'mon-063', title: 'Test leave-in thermometer', category: 'equipment', dueDate: '2026-06-15', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'mon-064', title: 'Test instant-read thermometer', category: 'equipment', dueDate: '2026-06-15', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'mon-065', title: 'Test sous vide circulator', category: 'equipment', dueDate: '2026-06-15', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'mon-066', title: 'Confirm sous vide container fits all tri-tip bags', category: 'equipment', dueDate: '2026-06-15', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'mon-067', title: 'Test slow cooker', category: 'equipment', dueDate: '2026-06-15', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'mon-068', title: 'Confirm carving board is large enough', category: 'equipment', dueDate: '2026-06-15', status: 'not_started', store: 'Home', priority: 'medium' },
  { id: 'mon-069', title: 'Confirm slicing knife is sharp', category: 'equipment', dueDate: '2026-06-15', status: 'not_started', store: 'Home', priority: 'medium' },
  { id: 'mon-070', title: 'Confirm extension cords and outlets are available', category: 'equipment', dueDate: '2026-06-15', status: 'not_started', store: 'Home', priority: 'medium' },
  { id: 'mon-071', title: 'Clear refrigerator space for cooked pork', category: 'prep', dueDate: '2026-06-15', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'mon-072', title: 'Make quick-pickled red onions (optional — can wait until Wed)', category: 'prep', dueDate: '2026-06-15', status: 'not_started', store: 'Home', priority: 'low', recipe: 'Quick-Pickled Red Onions' },

  // ── TUESDAY JUNE 16 ─────────────────────────────────────────────────────
  { id: 'tue-001', title: 'Confirm all Amazon orders will arrive before Friday', category: 'shopping', dueDate: '2026-06-16', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'tue-002', title: 'Confirm pinquito beans have arrived or are available locally', category: 'shopping', dueDate: '2026-06-16', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'tue-003', title: 'Confirm pork shoulder reservation', category: 'shopping', dueDate: '2026-06-16', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'tue-004', title: 'Confirm tri-tip reservation', category: 'shopping', dueDate: '2026-06-16', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'tue-005', title: 'Confirm cake order and pickup date', category: 'shopping', dueDate: '2026-06-16', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'tue-006', title: 'Confirm charcoal quantity is sufficient', category: 'shopping', dueDate: '2026-06-16', status: 'not_started', store: 'Home', priority: 'medium' },
  { id: 'tue-007', title: 'Confirm oak chunk supply', category: 'shopping', dueDate: '2026-06-16', status: 'not_started', store: 'Home', priority: 'medium' },
  { id: 'tue-008', title: 'Confirm vacuum bags fit tri-tip roasts', category: 'equipment', dueDate: '2026-06-16', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'tue-009', title: 'Confirm foil pans fit pork shoulders', category: 'equipment', dueDate: '2026-06-16', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'tue-010', title: 'Print or prepare buffet labels', category: 'setup', dueDate: '2026-06-16', status: 'not_started', store: 'Home', priority: 'medium' },
  { id: 'tue-011', title: 'Create and print spritz recipe card', category: 'setup', dueDate: '2026-06-16', status: 'not_started', store: 'Home', priority: 'low' },
  { id: 'tue-012', title: 'Create Wednesday fresh grocery shopping list', category: 'prep', dueDate: '2026-06-16', status: 'not_started', store: 'Home', priority: 'medium' },
  { id: 'tue-013', title: 'Create Friday fresh shopping list', category: 'prep', dueDate: '2026-06-16', status: 'not_started', store: 'Home', priority: 'medium' },

  // ── WEDNESDAY JUNE 17 ───────────────────────────────────────────────────
  { id: 'wed-001', title: 'Buy two bone-in pork shoulders', category: 'shopping', dueDate: '2026-06-17', status: 'not_started', store: 'Butcher', priority: 'high', quantity: '2 × 6–7 lb' },
  { id: 'wed-002', title: 'Buy tri-tip (if not already purchased)', category: 'shopping', dueDate: '2026-06-17', status: 'not_started', store: 'Butcher', priority: 'high', quantity: '5.5–6 lb total' },
  { id: 'wed-003', title: 'Buy Yukon Gold potatoes', category: 'shopping', dueDate: '2026-06-17', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '5 lb' },
  { id: 'wed-004', title: 'Buy celery stalks', category: 'shopping', dueDate: '2026-06-17', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '4 stalks' },
  { id: 'wed-005', title: 'Buy green onions or small red onion (potato salad)', category: 'shopping', dueDate: '2026-06-17', status: 'not_started', store: 'Grocery', priority: 'medium', quantity: '1 bunch or 1 onion' },
  { id: 'wed-006', title: 'Buy fresh dill', category: 'shopping', dueDate: '2026-06-17', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'wed-007', title: 'Buy flat-leaf parsley', category: 'shopping', dueDate: '2026-06-17', status: 'not_started', store: 'Grocery', priority: 'medium', quantity: '1 bunch' },
  { id: 'wed-008', title: 'Buy shredded cabbage or slaw mix', category: 'shopping', dueDate: '2026-06-17', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '2 lb' },
  { id: 'wed-009', title: 'Buy large yellow onion (for beans)', category: 'shopping', dueDate: '2026-06-17', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '1 large' },
  { id: 'wed-010', title: 'Buy Anaheim pepper or poblano (for beans)', category: 'shopping', dueDate: '2026-06-17', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '1' },
  { id: 'wed-011', title: 'Buy head of garlic', category: 'shopping', dueDate: '2026-06-17', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '1 head' },
  { id: 'wed-012', title: 'Buy bacon (for beans)', category: 'shopping', dueDate: '2026-06-17', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '8 oz' },
  { id: 'wed-013', title: 'Buy linguica — optional (for beans)', category: 'shopping', dueDate: '2026-06-17', status: 'not_started', store: 'Grocery', priority: 'low', quantity: '8 oz' },
  { id: 'wed-014', title: 'Buy extra red onions for pickling', category: 'shopping', dueDate: '2026-06-17', status: 'not_started', store: 'Grocery', priority: 'medium', quantity: '2–3' },
  { id: 'wed-015', title: 'Buy shallots', category: 'shopping', dueDate: '2026-06-17', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'wed-016', title: 'Buy missing pantry items', category: 'shopping', dueDate: '2026-06-17', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'wed-017', title: 'Make potato salad (refrigerate)', category: 'prep', dueDate: '2026-06-17', status: 'not_started', store: 'Home', priority: 'high', recipe: 'Vinegary Yukon Gold Potato Salad' },
  { id: 'wed-018', title: 'Make quick-pickled red onions (if not done Mon)', category: 'prep', dueDate: '2026-06-17', status: 'not_started', store: 'Home', priority: 'high', recipe: 'Quick-Pickled Red Onions' },
  { id: 'wed-019', title: 'Trim pork shoulders', category: 'prep', dueDate: '2026-06-17', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'wed-020', title: 'Season pork shoulders with rub — refrigerate uncovered overnight', category: 'prep', dueDate: '2026-06-17', status: 'not_started', store: 'Home', priority: 'high', recipe: 'Pork Shoulder Rub' },
  { id: 'wed-021', title: 'Organize serving vessels — match utensils to each dish', category: 'setup', dueDate: '2026-06-17', status: 'not_started', store: 'Home', priority: 'medium' },

  // ── THURSDAY JUNE 18 ────────────────────────────────────────────────────
  { id: 'thu-001', title: 'Verify pork cooking area is ready', category: 'prep', dueDate: '2026-06-18', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'thu-002', title: 'Set out charcoal, oak chunks, gloves, probes, foil, and pans', category: 'prep', dueDate: '2026-06-18', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'thu-003', title: 'Prepare shallow cooling pans for Friday pork', category: 'prep', dueDate: '2026-06-18', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'thu-004', title: 'Confirm refrigerator space for cooked pork', category: 'prep', dueDate: '2026-06-18', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'thu-005', title: 'Confirm slow cooker is ready for beans', category: 'equipment', dueDate: '2026-06-18', status: 'not_started', store: 'Home', priority: 'medium' },
  { id: 'thu-006', title: 'Sort and rinse 2 lb pinquito beans', category: 'prep', dueDate: '2026-06-18', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'thu-007', title: 'Soak 2 lb pinquito beans overnight in cold water', category: 'prep', dueDate: '2026-06-18', status: 'not_started', store: 'Home', priority: 'high', notes: 'Drain and cook Friday morning.' },
  { id: 'thu-008', title: 'Set alarm for 5:00 AM Friday pork cook', category: 'prep', dueDate: '2026-06-18', status: 'not_started', store: 'Home', priority: 'high' },

  // ── FRIDAY JUNE 19 ──────────────────────────────────────────────────────
  { id: 'fri-001', title: 'Remove pork from refrigerator', category: 'cooking', dueDate: '2026-06-19', dueTime: '05:00', timeBlock: '5:00 AM', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'fri-002', title: 'Light Slow \'N Sear — fill nearly full unlit, light 10–15 at one end', category: 'cooking', dueDate: '2026-06-19', dueTime: '05:00', timeBlock: '5:00 AM', status: 'not_started', store: 'Home', priority: 'high', notes: 'Target 260–285°F. Fill water reservoir with hot water. Top vent over meat. Bottom vent ¼ open, top vent ½ open.' },
  { id: 'fri-003', title: 'Place pork on grill (thicker side toward heat) — insert leave-in probe', category: 'cooking', dueDate: '2026-06-19', dueTime: '05:30', timeBlock: '5:30 AM', status: 'not_started', store: 'Home', priority: 'high', notes: 'Place 1 oak chunk over lit coals, 2 more partially buried farther along. Add 1–2 reserve chunks only if smoke disappears in first 3–4 hrs.' },
  { id: 'fri-004', title: 'Check cooker temp hourly — refill water reservoir as needed', category: 'cooking', dueDate: '2026-06-19', timeBlock: 'Ongoing', status: 'not_started', store: 'Home', priority: 'high', notes: 'Target 260–285°F. Rotate shoulders if one runs hotter. Lightly spritz if surface looks dry after 3 hrs (50/50 cider vinegar and water).' },
  { id: 'fri-005', title: 'Wrap pork in heavy foil when bark is set and IT is 165–175°F', category: 'cooking', dueDate: '2026-06-19', timeBlock: 'When ready', status: 'not_started', store: 'Home', priority: 'high', notes: 'Bark dark mahogany, rub does not wipe off, surface dry. Add ≤ ¼ cup broth/juice per shoulder inside wrap. No more oak after wrapping.' },
  { id: 'fri-006', title: 'Check doneness starting at 198°F — done at 198–205°F', category: 'cooking', dueDate: '2026-06-19', timeBlock: 'When ready', status: 'not_started', store: 'Home', priority: 'high', notes: 'Probe slides in with almost no resistance. Bone loosens easily.' },
  { id: 'fri-007', title: 'Rest pork wrapped for 45–60 min minimum', category: 'cooking', dueDate: '2026-06-19', timeBlock: 'After cook', status: 'not_started', store: 'Home', priority: 'high', notes: 'Can hold in 150–170°F oven or towel-lined dry cooler.' },
  { id: 'fri-008', title: 'Pull pork — save juices, remove bone, pull, cool in shallow pans ≤ 2 in deep', category: 'cooking', dueDate: '2026-06-19', timeBlock: 'After rest', status: 'not_started', store: 'Home', priority: 'high', notes: 'Defat reserved juices. Mix enough back in to moisten. Refrigerate uncovered until cold, then vacuum-seal or cover tightly.' },
  { id: 'fri-009', title: 'Drain soaked beans and cook until tender — reserve bean liquid', category: 'cooking', dueDate: '2026-06-19', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'fri-010', title: 'Make Santa Maria Pinquito Beans — cool and refrigerate', category: 'cooking', dueDate: '2026-06-19', status: 'not_started', store: 'Home', priority: 'high', recipe: 'Santa Maria Pinquito Beans' },
  { id: 'fri-011', title: 'Make vinegar slaw — refrigerate overnight', category: 'prep', dueDate: '2026-06-19', status: 'not_started', store: 'Home', priority: 'high', recipe: 'Vinegar Slaw' },
  { id: 'fri-012', title: 'Buy 24 slider buns', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Bakery', priority: 'high', quantity: '24' },
  { id: 'fri-013', title: 'Buy 12–16 sturdy rolls (ciabatta, French rolls)', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Bakery', priority: 'high', quantity: '12–16' },
  { id: 'fri-014', title: 'Buy 3 bunches flat-leaf parsley (chimichurri)', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '3 bunches' },
  { id: 'fri-015', title: 'Buy fresh oregano (optional for chimichurri)', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Grocery', priority: 'low' },
  { id: 'fri-016', title: 'Buy 1 shallot (chimichurri)', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Grocery', priority: 'medium', quantity: '1' },
  { id: 'fri-017', title: 'Buy garlic if needed', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Grocery', priority: 'medium' },
  { id: 'fri-018', title: 'Buy fresh slaw mix if Wed supply looks tired', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Grocery', priority: 'low', quantity: '2 lb' },
  { id: 'fri-019', title: 'Buy oranges (spritz garnish)', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Grocery', priority: 'medium', quantity: '4–6' },
  { id: 'fri-020', title: 'Buy lemons', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Grocery', priority: 'medium', quantity: '4' },
  { id: 'fri-021', title: 'Buy limes', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Grocery', priority: 'medium', quantity: '4–6' },
  { id: 'fri-022', title: 'Buy 2 bunches mint', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Grocery', priority: 'medium', quantity: '2 bunches' },
  { id: 'fri-023', title: 'Buy 2 containers berries', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Grocery', priority: 'low', quantity: '2 containers' },
  { id: 'fri-024', title: 'Pick up graduation cake', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Bakery', priority: 'high' },
  { id: 'fri-025', title: 'Buy prosecco or cava', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Liquor', priority: 'high', quantity: '5–6 bottles' },
  { id: 'fri-026', title: 'Buy dry white wine or rosé', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Liquor', priority: 'high', quantity: '2 bottles' },
  { id: 'fri-027', title: 'Buy Aperol', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Liquor', priority: 'high', quantity: '1 bottle' },
  { id: 'fri-028', title: 'Buy St-Germain elderflower liqueur', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Liquor', priority: 'high', quantity: '1 bottle' },
  { id: 'fri-029', title: 'Buy limoncello', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Liquor', priority: 'high', quantity: '1 bottle' },
  { id: 'fri-030', title: 'Buy soda water', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '6–8 liters' },
  { id: 'fri-031', title: 'Buy canned nonalcoholic drinks', category: 'shopping', dueDate: '2026-06-19', status: 'not_started', store: 'Grocery', priority: 'medium', quantity: '24–30' },
  { id: 'fri-032', title: 'Make chimichurri — refrigerate', category: 'prep', dueDate: '2026-06-19', status: 'not_started', store: 'Home', priority: 'high', recipe: 'Chimichurri' },
  { id: 'fri-033', title: 'Trim, season tri-tip — photograph grain change before bagging', category: 'prep', dueDate: '2026-06-19', status: 'not_started', store: 'Home', priority: 'high', recipe: 'Tri-Tip Seasoning' },
  { id: 'fri-034', title: 'Vacuum-seal tri-tip (no oil, no butter, no liquid smoke) — refrigerate', category: 'prep', dueDate: '2026-06-19', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'fri-035', title: 'Chill prosecco, wine, soda water, and nonalcoholic drinks', category: 'setup', dueDate: '2026-06-19', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'fri-036', title: 'Set out empty buffet vessels — match serving utensils to each dish', category: 'setup', dueDate: '2026-06-19', status: 'not_started', store: 'Home', priority: 'medium' },
  { id: 'fri-037', title: 'Place and fill buffet labels', category: 'setup', dueDate: '2026-06-19', status: 'not_started', store: 'Home', priority: 'medium' },
  { id: 'fri-038', title: 'Prepare spritz recipe card and place in holder', category: 'setup', dueDate: '2026-06-19', status: 'not_started', store: 'Home', priority: 'low' },
  { id: 'fri-039', title: 'Slice whole cherry peppers if needed', category: 'prep', dueDate: '2026-06-19', status: 'not_started', store: 'Home', priority: 'low' },
  { id: 'fri-040', title: 'Confirm ice plan for Saturday (need 40–50 lb total)', category: 'prep', dueDate: '2026-06-19', status: 'not_started', store: 'Home', priority: 'high', notes: 'Separate 15 lb for clean drink ice.' },
  { id: 'fri-041', title: 'Clear kitchen counters for party day', category: 'setup', dueDate: '2026-06-19', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'fri-042', title: 'Place bread baskets out (keep bread sealed until morning)', category: 'setup', dueDate: '2026-06-19', status: 'not_started', store: 'Home', priority: 'low' },
  { id: 'fri-043', title: 'Confirm charcoal is ready for Saturday sear', category: 'equipment', dueDate: '2026-06-19', status: 'not_started', store: 'Home', priority: 'high' },

  // ── SATURDAY JUNE 20 ────────────────────────────────────────────────────
  { id: 'sat-001', title: 'Buy 40–50 lb ice (separate 15 lb for clean drink ice)', category: 'shopping', dueDate: '2026-06-20', timeBlock: 'Morning', status: 'not_started', store: 'Grocery', priority: 'high', quantity: '40–50 lb' },
  { id: 'sat-002', title: 'Buy emergency extra buns (only if headcount increased)', category: 'shopping', dueDate: '2026-06-20', timeBlock: 'Morning', status: 'not_started', store: 'Bakery', priority: 'low' },

  { id: 'sat-003', title: 'Clear kitchen workspace', category: 'setup', dueDate: '2026-06-20', dueTime: '09:30', timeBlock: '9:30 AM', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'sat-004', title: 'Set out buffet vessels', category: 'setup', dueDate: '2026-06-20', dueTime: '09:30', timeBlock: '9:30 AM', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'sat-005', title: 'Set up water station', category: 'setup', dueDate: '2026-06-20', dueTime: '09:30', timeBlock: '9:30 AM', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'sat-006', title: 'Place drinks in coolers', category: 'setup', dueDate: '2026-06-20', dueTime: '09:30', timeBlock: '9:30 AM', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'sat-007', title: 'Assemble empty spritz bar', category: 'setup', dueDate: '2026-06-20', dueTime: '09:30', timeBlock: '9:30 AM', status: 'not_started', store: 'Home', priority: 'medium' },
  { id: 'sat-008', title: 'Check pork, beans, potato salad, slaw, and toppings', category: 'prep', dueDate: '2026-06-20', dueTime: '09:30', timeBlock: '9:30 AM', status: 'not_started', store: 'Home', priority: 'high' },

  { id: 'sat-009', title: 'Set sous vide bath to 132°F', category: 'cooking', dueDate: '2026-06-20', dueTime: '10:30', timeBlock: '10:30 AM', status: 'not_started', store: 'Home', priority: 'high', notes: '4-hour cook. Acceptable range 3.5–5 hrs. Done ~2:30 PM.' },
  { id: 'sat-010', title: 'Add tri-tip bags to sous vide', category: 'cooking', dueDate: '2026-06-20', dueTime: '10:30', timeBlock: '10:30 AM', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'sat-011', title: 'Start 4-hour sous vide timer', category: 'cooking', dueDate: '2026-06-20', dueTime: '10:30', timeBlock: '10:30 AM', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'sat-012', title: 'Taste potato salad — adjust seasoning and return to refrigerator', category: 'prep', dueDate: '2026-06-20', dueTime: '10:30', timeBlock: '10:30 AM', status: 'not_started', store: 'Home', priority: 'medium' },

  { id: 'sat-013', title: 'Transfer pulled pork to covered foil pans — add reserved juices', category: 'cooking', dueDate: '2026-06-20', dueTime: '11:00', timeBlock: '11:00 AM', status: 'not_started', store: 'Home', priority: 'high', notes: 'Keep refrigerated until 1:30 PM.' },
  { id: 'sat-014', title: 'Transfer pinquito beans to slow cooker — keep off until 1:30 PM', category: 'cooking', dueDate: '2026-06-20', dueTime: '11:00', timeBlock: '11:00 AM', status: 'not_started', store: 'Home', priority: 'high' },

  { id: 'sat-015', title: 'Drain pickles, jalapeños, and cherry peppers', category: 'prep', dueDate: '2026-06-20', dueTime: '12:00', timeBlock: '12:00 PM', status: 'not_started', store: 'Home', priority: 'medium' },
  { id: 'sat-016', title: 'Fill labeled topping containers — set up backup refill containers', category: 'setup', dueDate: '2026-06-20', dueTime: '12:00', timeBlock: '12:00 PM', status: 'not_started', store: 'Home', priority: 'medium' },
  { id: 'sat-017', title: 'Cut spritz garnishes (orange, lemon, lime, mint)', category: 'prep', dueDate: '2026-06-20', dueTime: '12:00', timeBlock: '12:00 PM', status: 'not_started', store: 'Home', priority: 'medium' },
  { id: 'sat-018', title: 'Fill clean drink-ice bucket — fill beverage tub with bottle ice', category: 'setup', dueDate: '2026-06-20', dueTime: '12:00', timeBlock: '12:00 PM', status: 'not_started', store: 'Home', priority: 'high', notes: 'Keep drink ice separate from bottle-chilling ice.' },

  { id: 'sat-019', title: 'Preheat oven to 275°F — put covered pork in oven', category: 'cooking', dueDate: '2026-06-20', dueTime: '13:30', timeBlock: '1:30 PM', status: 'not_started', store: 'Home', priority: 'high', notes: 'Reheat 60–90 min. Stir once at 45 min. Heat to 165°F then hold at 150–170°F.' },
  { id: 'sat-020', title: 'Turn slow cooker with beans to high', category: 'cooking', dueDate: '2026-06-20', dueTime: '13:30', timeBlock: '1:30 PM', status: 'not_started', store: 'Home', priority: 'high', notes: 'Stir periodically. Hold above 140°F.' },
  { id: 'sat-021', title: 'Start pork reheat timer (90 min)', category: 'cooking', dueDate: '2026-06-20', dueTime: '13:30', timeBlock: '1:30 PM', status: 'not_started', store: 'Home', priority: 'high' },

  { id: 'sat-022', title: 'Set up spritz bar fully — put prosecco and wine in ice', category: 'setup', dueDate: '2026-06-20', dueTime: '14:00', timeBlock: '2:00 PM', status: 'not_started', store: 'Home', priority: 'high', notes: 'Aperol, St-Germain, limoncello out. Soda water and no-proof mixers out. Garnishes, recipe card, napkins, wine key, water.' },
  { id: 'sat-023', title: 'Place trash and recycling bins in visible accessible spots', category: 'setup', dueDate: '2026-06-20', dueTime: '14:00', timeBlock: '2:00 PM', status: 'not_started', store: 'Home', priority: 'medium' },

  { id: 'sat-024', title: 'Check pork temperature and stir', category: 'cooking', dueDate: '2026-06-20', dueTime: '14:30', timeBlock: '2:30 PM', status: 'not_started', store: 'Home', priority: 'high', notes: 'Target 165°F. Hold at 150–170°F.' },
  { id: 'sat-025', title: 'Check bean consistency — loosen with bean liquid or broth if needed', category: 'cooking', dueDate: '2026-06-20', dueTime: '14:30', timeBlock: '2:30 PM', status: 'not_started', store: 'Home', priority: 'medium', notes: 'Loose and spoonable, not soupy. Hold above 140°F.' },
  { id: 'sat-026', title: 'Move cold dishes into serving bowls (keep refrigerated until closer)', category: 'setup', dueDate: '2026-06-20', dueTime: '14:30', timeBlock: '2:30 PM', status: 'not_started', store: 'Home', priority: 'medium' },
  { id: 'sat-027', title: 'Bring chimichurri toward room temperature — taste and adjust', category: 'prep', dueDate: '2026-06-20', dueTime: '14:30', timeBlock: '2:30 PM', status: 'not_started', store: 'Home', priority: 'medium' },

  { id: 'sat-028', title: 'Light ⅓–½ chimney of charcoal — pour into Slow \'N Sear', category: 'cooking', dueDate: '2026-06-20', dueTime: '14:45', timeBlock: '2:45 PM', status: 'not_started', store: 'Home', priority: 'high', notes: 'Water reservoir EMPTY. Open vents fully. Concentrate coals into deep compact pile.' },
  { id: 'sat-029', title: 'Put buns into lined baskets', category: 'setup', dueDate: '2026-06-20', dueTime: '14:45', timeBlock: '2:45 PM', status: 'not_started', store: 'Home', priority: 'medium' },
  { id: 'sat-030', title: 'Fill sauce pitchers and topping ramekins', category: 'setup', dueDate: '2026-06-20', dueTime: '14:45', timeBlock: '2:45 PM', status: 'not_started', store: 'Home', priority: 'medium' },

  { id: 'sat-031', title: 'Remove tri-tip from sous vide — pat completely dry', category: 'cooking', dueDate: '2026-06-20', dueTime: '15:00', timeBlock: '3:00 PM', status: 'not_started', store: 'Home', priority: 'high', notes: 'Refrigerate uncovered 20–30 min OR freezer 8–10 min. Add light fresh black pepper if desired.' },
  { id: 'sat-032', title: 'Put potato salad, slaw, pickles, and peppers on buffet', category: 'setup', dueDate: '2026-06-20', dueTime: '15:00', timeBlock: '3:00 PM', status: 'not_started', store: 'Home', priority: 'high' },

  { id: 'sat-033', title: 'Sear tri-tip over extremely hot coals — total 2–3 min direct exposure', category: 'cooking', dueDate: '2026-06-20', dueTime: '15:10', timeBlock: '3:10 PM', status: 'not_started', store: 'Home', priority: 'high', notes: '20–30 sec per contact. Flip frequently. Rotate grate. Sear broad sides, fat cap, and edges. Avoid sustained flare-ups.' },

  { id: 'sat-034', title: 'Rest tri-tip 8–10 minutes — do NOT tent tightly with foil', category: 'cooking', dueDate: '2026-06-20', dueTime: '15:15', timeBlock: '3:15 PM', status: 'not_started', store: 'Home', priority: 'high' },

  { id: 'sat-035', title: 'Separate tri-tip at grain change — slice each section across grain ⅛ in thick', category: 'serving', dueDate: '2026-06-20', dueTime: '15:20', timeBlock: '3:20 PM', status: 'not_started', store: 'Home', priority: 'high', notes: 'Slice only ⅓–½ initially. Keep rest whole until needed.' },
  { id: 'sat-036', title: 'Transfer pork to serving vessel — transfer beans to station', category: 'serving', dueDate: '2026-06-20', dueTime: '15:20', timeBlock: '3:20 PM', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'sat-037', title: 'Put chimichurri, BBQ sauces, and bread baskets on buffet', category: 'serving', dueDate: '2026-06-20', dueTime: '15:20', timeBlock: '3:20 PM', status: 'not_started', store: 'Home', priority: 'high' },

  { id: 'sat-038', title: '🎉 BEGIN FOOD SERVICE', category: 'serving', dueDate: '2026-06-20', dueTime: '15:30', timeBlock: '3:30 PM', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'sat-039', title: 'Replenish tri-tip in small batches', category: 'serving', dueDate: '2026-06-20', dueTime: '15:30', timeBlock: '3:30 PM', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'sat-040', title: 'Stir pork periodically — refill toppings as needed', category: 'serving', dueDate: '2026-06-20', dueTime: '15:30', timeBlock: '3:30 PM', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'sat-041', title: 'Monitor hot-food temps — keep cold foods out of direct sun', category: 'serving', dueDate: '2026-06-20', dueTime: '15:30', timeBlock: '3:30 PM', status: 'not_started', store: 'Home', priority: 'high', notes: 'Perishables max 2 hrs out (shorter in heat/direct sun). Pork and beans must stay above 140°F.' },

  { id: 'sat-042', title: 'Refrigerate pork in shallow containers (freeze extra with reserved juice)', category: 'cleanup', dueDate: '2026-06-20', timeBlock: 'After Party', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'sat-043', title: 'Refrigerate beans, potato salad, chimichurri, and pickled toppings', category: 'cleanup', dueDate: '2026-06-20', timeBlock: 'After Party', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'sat-044', title: 'Discard any food left out too long', category: 'cleanup', dueDate: '2026-06-20', timeBlock: 'After Party', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'sat-045', title: 'Extinguish charcoal by closing all vents — save reusable charcoal once cold', category: 'cleanup', dueDate: '2026-06-20', timeBlock: 'After Party', status: 'not_started', store: 'Home', priority: 'high' },
  { id: 'sat-046', title: 'Wash bread baskets, ramekins, and beverage equipment', category: 'cleanup', dueDate: '2026-06-20', timeBlock: 'After Party', status: 'not_started', store: 'Home', priority: 'medium' },
]

export const INITIAL_TIMERS: Timer[] = [
  { id: 'timer-sv',       label: 'Sous Vide — Tri-Tip',  durationMinutes: 240, isRunning: false, notes: '132°F · Start at 10:30 AM · Done ~2:30 PM · Acceptable range 3.5–5 hrs' },
  { id: 'timer-pork',     label: 'Pork Reheat',           durationMinutes: 90,  isRunning: false, notes: '275°F oven · Start at 1:30 PM · Stir at 45 min · Target 165°F' },
  { id: 'timer-charcoal', label: 'Charcoal Lighting',     durationMinutes: 20,  isRunning: false, notes: 'Start at 2:45 PM · ⅓–½ chimney · Coals fully ashed over before sear' },
  { id: 'timer-dry',      label: 'Tri-Tip Drying',        durationMinutes: 25,  isRunning: false, notes: 'Fridge 20–30 min OR freezer 8–10 min · Remove from sous vide at 3:00 PM' },
  { id: 'timer-sear',     label: 'Tri-Tip Sear',          durationMinutes: 3,   isRunning: false, notes: '20–30 sec per contact · Flip frequently · Total ~2–3 min direct heat' },
  { id: 'timer-rest',     label: 'Tri-Tip Rest',          durationMinutes: 10,  isRunning: false, notes: 'Do NOT tent tightly · Start at 3:15 PM · Done by 3:25 PM' },
]

export const RECIPES: Recipe[] = [
  {
    id: 'pickled-onions',
    name: 'Quick-Pickled Red Onions',
    ingredients: ['2–3 red onions, thinly sliced', '1½ cups vinegar', '1½ cups water', '3 tbsp sugar', '1½ tbsp kosher salt'],
    steps: ['Warm vinegar, water, sugar, and salt until dissolved.', 'Pour over sliced onions.', 'Cool to room temperature.', 'Refrigerate.', 'Keep refrigerated through party day.'],
    notes: 'Make Monday or Wednesday. Keeps all week.',
  },
  {
    id: 'potato-salad',
    name: 'Vinegary Yukon Gold Potato Salad',
    ingredients: ['5 lb Yukon Gold potatoes', '½ cup white wine or cider vinegar', '½ cup extra-virgin olive oil', '2 tbsp whole-grain mustard', '1 tbsp Dijon mustard', '1 tbsp sugar', '1½ tsp kosher salt', '½ tsp black pepper', '1 small red onion or 1 bunch green onions', '4 celery stalks', '½ cup chopped dill and flat-leaf parsley', 'Optional: 6 slices cooked bacon'],
    steps: ['Cut potatoes into 1-inch pieces.', 'Boil in salted water until just fork-tender. Drain.', 'Toss warm potatoes with vinegar first.', 'Add oil, mustards, sugar, salt, and pepper.', 'Fold in onion, celery, and herbs.', 'Refrigerate.', 'Adjust salt and acidity Saturday before serving.'],
    notes: 'Make Wednesday. No mayonnaise. Serve cool or near room temperature.',
  },
  {
    id: 'pork-rub',
    name: 'Pork Shoulder Rub (per 6–7 lb shoulder)',
    ingredients: ['1½ tbsp Diamond Crystal kosher salt', '2 tbsp brown sugar', '2 tbsp paprika', '1 tbsp coarse black pepper', '2 tsp granulated garlic', '2 tsp onion powder', '1 tsp cumin', '1 tsp chili powder'],
    steps: ['Trim loose flaps and hard fat — leave most fat intact.', 'Combine all rub ingredients.', 'Coat all surfaces evenly.', 'Refrigerate uncovered overnight.', 'Smoke Friday starting 5:30 AM at 260–285°F.'],
    notes: 'Apply Wednesday night. Double the recipe for two shoulders.',
  },
  {
    id: 'pinquito-beans',
    name: 'Santa Maria Pinquito Beans',
    ingredients: ['2 lb dried pinquito beans (soaked overnight)', '8 oz bacon, diced', 'Optional: 8 oz linguica, diced', '1 large yellow onion, diced', '4 garlic cloves, minced', '1 Anaheim pepper or poblano, diced', '28 oz crushed tomatoes', '15 oz tomato sauce', '2 tbsp tomato paste', '2 tbsp chili powder', '2 tsp ground cumin', '1 tsp dried oregano', '½ tsp cayenne (optional)', '2 tsp kosher salt', '1 tsp black pepper', '2 tbsp brown sugar', '2 tbsp cider vinegar', '1 tbsp Worcestershire sauce', 'Reserved bean cooking liquid'],
    steps: ['Drain soaked beans. Cover with fresh water and simmer until tender but intact. Reserve several cups liquid.', 'Cook bacon until lightly crisp. Add linguica if using.', 'Add onion and pepper; cook until softened. Add garlic; cook 1 min.', 'Add tomato paste and spices; stir to coat.', 'Add crushed tomatoes, sauce, sugar, vinegar, and Worcestershire.', 'Add beans and bean liquid until saucy.', 'Simmer 30–45 minutes. Adjust salt, vinegar, sugar, and heat.', 'Cool and refrigerate Friday. Reheat in slow cooker Saturday.'],
    notes: 'Hold warm above 140°F. Should be loose and spoonable, not soupy.',
  },
  {
    id: 'chimichurri',
    name: 'Chimichurri',
    ingredients: ['2 packed cups flat-leaf parsley, finely chopped', '¼ cup fresh oregano or 1 tbsp dried', '4 garlic cloves, finely minced', '1 small shallot, finely minced', '½ tsp red pepper flakes', '⅓ cup red wine vinegar', '¾ cup extra-virgin olive oil', '1 tsp Diamond Crystal kosher salt', '½ tsp black pepper'],
    steps: ['Combine parsley, oregano, garlic, shallot, red pepper flakes, vinegar, salt, and pepper.', 'Rest 10 minutes.', 'Stir in olive oil.', 'Refrigerate.', 'Bring near room temperature before serving.', 'Taste and adjust salt and vinegar.'],
    notes: 'Make Friday evening. Bring toward room temperature at 2:30 PM Saturday.',
  },
  {
    id: 'vinegar-slaw',
    name: 'Vinegar Slaw',
    ingredients: ['2 lb shredded cabbage or slaw mix', '¾ cup cider vinegar', '⅓ cup neutral oil', '3 tbsp sugar', '1½ tsp kosher salt', '1 tsp celery seed', '½ tsp black pepper'],
    steps: ['Whisk vinegar, oil, sugar, salt, celery seed, and pepper into a dressing.', 'Toss with cabbage.', 'Refrigerate overnight.', 'Taste and adjust before serving.'],
    notes: 'Make Friday. Serves as both a side and a pulled pork sandwich topping.',
  },
  {
    id: 'tritip-seasoning',
    name: 'Tri-Tip Seasoning (per pound)',
    ingredients: ['¾ tsp Diamond Crystal kosher salt', '½ tsp coarse black pepper', '½ tsp granulated garlic', '⅛ tsp onion powder', 'Small pinch dried rosemary (optional)'],
    steps: ['Trim silverskin and most hard fat — leave a thin fat layer.', 'Identify both grain directions. Photograph or mark the grain-direction change.', 'Season evenly on all surfaces.', 'Vacuum-seal — no oil, no butter, no liquid smoke.', 'Refrigerate overnight.', 'Sous vide Saturday at 132°F for 4 hours (acceptable 3.5–5 hrs).'],
    notes: 'The grain runs in two directions. Mark the change point before bagging — critical for slicing Saturday.',
  },
  {
    id: 'spritzes',
    name: 'Spritz Bar Recipes',
    ingredients: [
      '── Aperol Spritz ──', '3 oz prosecco', '2 oz Aperol', '1 oz soda water', 'Orange slice',
      '── Hugo Spritz ──', '3 oz prosecco', '1½ oz St-Germain', '1 oz soda water', 'Mint + lime',
      '── Limoncello Spritz ──', '3 oz prosecco', '1–1½ oz limoncello', '1 oz soda water', 'Lemon slice',
      '── Wine Spritzer ──', 'Equal parts chilled wine and soda water', 'Citrus or berries',
      '── No-Proof Spritz ──', 'Elderflower or grapefruit soda', 'Soda water', 'Lime and mint',
    ],
    steps: ['Build all spritzes in a large wine glass over ice.', 'Add spirit or liqueur first, then sparkling wine or soda.', 'Add garnish last.', 'Print this recipe and display at the spritz bar in the card holder.'],
    notes: 'Set up spritz bar at 2:00 PM. Keep prosecco and wine chilled in ice.',
  },
]
